### PR TITLE
STOR-1020: Rebase `external-attacher` to v4.1.0 for OCP 4.13

### PR DESCRIPTION
**Pull request by mpatlasov**
Diff to upstream v4.1.0:
https://github.com/kubernetes-csi/external-attacher/compare/v4.1.0...mpatlasov:rebase-4.1.0

Major changes between 4.0.0 (OCP 4.12) and 4.1.0:

Updated Kubernetes dependencies to 1.26.0 (https://github.com/kubernetes-csi/external-attacher/pull/395, [@sunnylovestiramisu](https://github.com/sunnylovestiramisu))

Full changelogs:

https://github.com/kubernetes-csi/external-attacher/releases/tag/v4.1.0

@storage-team

### CODE REVIEW

**Comment by mpatlasov** [comment]
Build Log:
> error: unable to retrieve the complete list of server APIs: user.openshift.io/v1: the server is currently unable to handle the request
/retest

**Comment by dobsonj** [comment]
/label docs-approved
/label px-approved
generally no user facing impact from sidecar rebases

**Comment by mpatlasov** [comment]
/retitle STOR-1020: Rebase `external-attacher` to v4.1.0 for OCP 4.13

**Comment by duanwei33** [comment]
The CI result looks good enough for the rebase PR.

**Pull request merged**
