### PR TITLE
STOR-2018: Rebase external-attacher to v4.7.0 for OCP 4.18

### PR DESCRIPTION
**Pull request by rhrmo**
Diff to upstream 4.7.0:
https://github.com/kubernetes-csi/external-attacher/compare/v4.7.0...rhrmo:rebase-4.7.0

Changes between 4.6.1 (OCP 4.17) and 4.7.0 (OCP 4.18):
* https://github.com/kubernetes-csi/external-attacher/pull/561
* https://github.com/kubernetes-csi/external-attacher/pull/577
* https://github.com/kubernetes-csi/external-attacher/pull/573

Full changelogs:
https://github.com/kubernetes-csi/external-attacher/blob/release-4.7/CHANGELOG/CHANGELOG-4.7.md

@openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
@rhrmo I think you missed this commit: https://github.com/openshift/csi-external-attacher/commit/5bbf33ec14ccd4ca33673bdac70614df9fb52383

OpenShift's Dockerfile is now `Dockerfile.ocp` and not `Dockerfile.openshift.rhel7`. The error messages in CI could have been more obvious :-\

**Comment by rhrmo** [comment]
@jsafrane it does not show up when I search through commits from last common ancestor:
```
git log $( git merge-base openshift/master v4.7.0 )..openshift/master --reverse --ancestry-path --no-merges --pretty='tformat:%x09%h%x09%x09%x09%s' 
```
but you are right, it should be there, I think... is just adding the commit in it's proper order enough?

**Comment by jsafrane** [comment]
squash everything into `<carry>: Add OpenShift files`

**Comment by duanwei33** [comment]
The CI result looks good.
/label qe-approved

**Pull request merged**
