### PR TITLE
STOR-1593: Rebase external-attacher to v4.6.1 for OCP 4.17

### PR DESCRIPTION
**Pull request by dfajmon**
Diff to upstream 4.6.1:
https://github.com/kubernetes-csi/external-attacher/compare/v4.6.1...dfajmon:rebase-4.6.1

Changes between 4.5.1 (OCP 4.16) and 4.6.1 (OCP 4.17):
- https://github.com/kubernetes-csi/external-attacher/pull/549
- https://github.com/kubernetes-csi/external-attacher/pull/564
- https://github.com/kubernetes-csi/external-attacher/pull/555 fixes https://github.com/advisories/GHSA-2jwv-jmq4-4j3r

Full changelogs:
https://github.com/kubernetes-csi/external-attacher/releases/tag/v4.6.1

@openshift/storage

### CODE REVIEW

**Comment by RomanBednar** [comment]
@dfajmon Please fix the descriptions: 

`Changes between 4.5.1 (OCP 4.17) and 4.6.1:` -> should be `Changes between 4.5.1 (OCP 4.16) and 4.6.1:`
`Rebase external-attacher to v4.6.1 for OCP 4.18` -> should be `Rebase external-attacher to v4.6.1 for OCP 4.17`

Otherwise the PR looks good, but the CI will keep failing until we have go 1.22.3 in CI: https://issues.redhat.com/browse/ART-9927

**Comment by duanwei33** [comment]
CI looks good.
/label qe-approved

**Pull request merged**
