### PR TITLE
STOR-1404: Rebase `external-attacher` to v4.4.0 for OCP 4.15

### PR DESCRIPTION
**Pull request by mpatlasov**
Diff to upstream v4.4.0:
https://github.com/kubernetes-csi/external-attacher/compare/v4.4.0...mpatlasov:rebase-v4.4.0

Changes between 4.3.0 (OCP 4.14) and 4.4.0:

 * Add --max-entries flag to limit ListVolumes request entries per page (#462, @kayrus)
 * Update kubernetes dependencies to v1.28.0 (#475, @Sneha-at)

Full changelogs:

https://github.com/kubernetes-csi/external-attacher/releases/tag/v4.4.0

@openshift/storage

### CODE REVIEW

**Comment by gnufied** [comment]
@mpatlasov are these verify failures legit?

**Comment by mpatlasov** [comment]
> @mpatlasov are these verify failures legit?

If you ask about `ci/prow/verify-commits`, then no, I don't think these test failure is legit. @jsafrane commented [here](https://github.com/openshift/aws-ebs-csi-driver/pull/232#issuecomment-1689850837) that we have to override this test for rebases:

/override ci/prow/verify-commits

**Comment by jsafrane** [comment]
/retest
> operator "cluster-network-operator" contained an invalid image-references file: no input image tag named "kuryr-cni"

??

**Pull request merged**
