### PR TITLE
Bug 1924432: Rebase v3.2.1

### PR DESCRIPTION
**Pull request by jsafrane**
Rebase to the latest external-attacher v3.2.1 for OCP 4.8.

https://github.com/kubernetes-csi/external-attacher/compare/v3.2.1...jsafrane:rebase-v3.2.0

cc @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
Filed https://bugzilla.redhat.com/show_bug.cgi?id=1959470 for oVirt errors.

**Review by tsmetana — APPROVED** [review]
/lgtm

**Pull request merged**
